export {Home} from './Home';
export {About} from './About';
export {Cart} from './Cart';
export {Drops} from './Drops';
export {Contact} from './Contact';
export {Login} from './Login';
export {Orders} from './Orders';
export {PlaceOrder} from './PlaceOrder';
export {Product} from './Product';